name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build
      run: g++ -Wall -Wextra -Werror --coverage  -o Sender sender/sender.cpp
    
    - name: build
      run: g++ -Wall -Wextra -Werror --coverage  -o Receiver receiver/receiver.cpp
      
    - name: build Sender Test
      run: g++ -Wall -Wextra -Werror -o SenderTest Sender_Test/*.cpp
      
    - name: build Receiver Test
      run: g++ -Wall -Wextra -Werror -o ReceiverTest Sender_Test/*.cpp
            
    - name: static analysis
      run: cppcheck --enable=all --check-config --error-exitcode=1 .
      
    - name: run
      run: ./Sender | ./Receiver
    
    - name: run Sender Test
      run: ./SenderTest
    
    - name: run Receiver Test
      run: ./ReceiverTest
    
    - name: coverage report sender
      run: gcov -r sender.cpp
      
    - name: coverage report Receiver
      run: gcov -r receiver.cpp
